version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:443
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    certificate: /certs/registry_auth.crt
    key: /certs/registry_auth.key
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  token:
    realm: https://registry.example.com:5001/auth
    service: registry.example.com:443
    issuer: "Registry server"
    rootcertbundle: /certs/docker_auth.crt
